In [0]:
import pandas as pd

In [0]:
file = pd.read_csv('quora_supervised.csv')

In [3]:
file.head()

Unnamed: 0  ...                                         Topic desc
0           0  ...                   Education, Schools, and Learning
1           1  ...           Politics, Law, Government, and Judiciary
2           2  ...                                         Humanities
3           3  ...                            Medicine and Healthcare
4           4  ...  Science, Technology, Engineering, and Mathematics

[5 rows x 4 columns]

In [4]:
file['Topic number'].value_counts()

9    43295
8    27587
0    24339
5    23906
1    23888
7    13341
6    12337
3    10898
2    10490
4     9919
Name: Topic number, dtype: int64

In [5]:
file.sample(10)

Unnamed: 0  ...                                         Topic desc
140011      140011  ...  Science, Technology, Engineering, and Mathematics
17679        17679  ...                      Life, Relationships, and Self
24427        24427  ...                            Medicine and Healthcare
177324      177324  ...                   Education, Schools, and Learning
52130        52130  ...                   Education, Schools, and Learning
47762        47762  ...                            Medicine and Healthcare
28383        28383  ...                                         horoscopes
193267      193267  ...                            Medicine and Healthcare
25420        25420  ...                            Medicine and Healthcare
160795      160795  ...                                         Humanities

[10 rows x 4 columns]

### Pre-processing the dataset

In [0]:
# Splitting the data into train and test

from sklearn.model_selection import train_test_split 
X = file['questions']
y = file['Topic number']
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 1)

In [7]:
type(X_test)

pandas.core.series.Series

In [8]:
# Vectorizing the string data into numerical data

from sklearn.feature_extraction.text import TfidfVectorizer
vectorizer = TfidfVectorizer()

train_vectors = vectorizer.fit_transform(X_train)
#test_vectors = vectorizer.fit_transform(X_test)
test_vectors = vectorizer.transform(X_test)
print(train_vectors.shape, test_vectors.shape)

(160000, 45994) (40000, 45994)


### Logistic Regression

In [9]:
# Logistic Regression
from sklearn.linear_model import LogisticRegression

lin_reg_model = LogisticRegression(solver = 'lbfgs')
lin_reg_model.fit(train_vectors, y_train)

/usr/local/lib/python3.6/dist-packages/sklearn/linear_model/_logistic.py:940: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG)


LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=100,
                   multi_class='auto', n_jobs=None, penalty='l2',
                   random_state=None, solver='lbfgs', tol=0.0001, verbose=0,
                   warm_start=False)

In [0]:
# Test Accuracy

from sklearn import metrics
lin_reg_model_predictions = lin_reg_model.predict(test_vectors)

In [11]:
lin_reg_model_predictions

array([8, 4, 6, ..., 9, 0, 4])

In [12]:
print(metrics.confusion_matrix(y_test, lin_reg_model_predictions))

[[4396   39   15    8   13   58   30   10  131  171]
 [  30 4106   14   10   10   82   19   14  123  303]
 [  24   41 1786    5    9   31   16   16   87  133]
 [  36   42   18 1835    2   69    4    9   72  119]
 [  13   44    1    6 1688   48    9    8   54  133]
 [  42   67   13   25   15 4193   18   16  110  305]
 [  26   37   19    8    5   40 2102   15  102  142]
 [  22   38    5    2   11   76    8 2280   43  170]
 [  65   85   13   17   21  113   31    7 4800  266]
 [  55   89   37   10   30  137   25   40  133 8131]]


In [13]:
print(metrics.accuracy_score(y_test,lin_reg_model_predictions))

0.882925


In [14]:
print(metrics.classification_report(y_test, lin_reg_model_predictions))

              precision    recall  f1-score   support

           0       0.93      0.90      0.92      4871
           1       0.89      0.87      0.88      4711
           2       0.93      0.83      0.88      2148
           3       0.95      0.83      0.89      2206
           4       0.94      0.84      0.89      2004
           5       0.87      0.87      0.87      4804
           6       0.93      0.84      0.88      2496
           7       0.94      0.86      0.90      2655
           8       0.85      0.89      0.87      5418
           9       0.82      0.94      0.88      8687

    accuracy                           0.88     40000
   macro avg       0.91      0.87      0.88     40000
weighted avg       0.89      0.88      0.88     40000



logistic regression give us the accuracy of 88 percent.

### Random Forest

In [15]:
# Random Forrest

# Step 1: Import the model
from sklearn.ensemble import RandomForestClassifier 

# Step 2: Create an instance of the model
RFC_model = RandomForestClassifier()

# Step 3: Build the model and fit the data
RFC_model.fit(train_vectors, y_train)

RandomForestClassifier(bootstrap=True, ccp_alpha=0.0, class_weight=None,
                       criterion='gini', max_depth=None, max_features='auto',
                       max_leaf_nodes=None, max_samples=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, n_estimators=100,
                       n_jobs=None, oob_score=False, random_state=None,
                       verbose=0, warm_start=False)

In [0]:
RFC_model_predictions = RFC_model.predict(test_vectors)

In [46]:
print(metrics.accuracy_score(y_test,RFC_model_predictions))

0.84945


Random Forest gives us the accuracy of 88 percent.

### Naive Bayes

In [17]:
# Naive Bayes

# Step 1: Import the model
from sklearn.naive_bayes import MultinomialNB

# Step 2: Create an instance of the model
nb_model = MultinomialNB()

# Step 3: Build the model and fit the data
nb_model.fit(train_vectors, y_train)

MultinomialNB(alpha=1.0, class_prior=None, fit_prior=True)

In [0]:
nb_model_predictions = nb_model.predict(test_vectors)

In [19]:
print(metrics.accuracy_score(y_test,nb_model_predictions))

0.6557


Naive Bayes gives us the lowest accuracy against all models

In [20]:
print(metrics.classification_report(y_test, nb_model_predictions))

              precision    recall  f1-score   support

           0       0.72      0.72      0.72      4871
           1       0.79      0.61      0.69      4711
           2       0.95      0.44      0.60      2148
           3       0.94      0.32      0.48      2206
           4       0.96      0.31      0.47      2004
           5       0.72      0.66      0.69      4804
           6       0.90      0.52      0.66      2496
           7       0.90      0.44      0.59      2655
           8       0.64      0.72      0.68      5418
           9       0.51      0.92      0.65      8687

    accuracy                           0.66     40000
   macro avg       0.80      0.57      0.62     40000
weighted avg       0.73      0.66      0.65     40000



As from the results we know that logistic regression has highest accuracy so we test it out by giving it sample questions

In [25]:
sample_questions = test_vectors[3]
test_vectors[2]

<1x45994 sparse matrix of type '<class 'numpy.float64'>'
	with 10 stored elements in Compressed Sparse Row format>

In [26]:
model_predictions = lin_reg_model.predict(sample_questions)
out_dataframe = pd.DataFrame(model_predictions)
out_dataframe

0
0  9

**Choosing 10 random questions**

In [27]:
sample_question = X_train.sample(10)
sample_question

148099    What will be the effects of demonitizing 500 a...
16512                                Why is NASCAR a sport?
14884     What's your view on the infamous Jayalalitha S...
169255        Should people over 94 not be allowed to vote?
187649           What's the latest trend for SEO this 2014?
161680    What were the major effects of the cambodia ea...
43258          Do virtual particles in vacuum really exist?
185017    What is the salary scenario in pharmacovigilan...
11887     Do all national servicemen in Singapore have t...
37895      What is the best way to learn computer language?
Name: questions, dtype: object

In [0]:
vector_samples = vectorizer.transform(sample_question)

In [0]:
sample_predictions = lin_reg_model.predict(vector_samples)# we use linear regression bcz it has high accuracy than anyother model

In [0]:
out_dataframe = pd.DataFrame(sample_predictions,sample_question)

In [34]:
topic_list = { 0 : 'Technology',
               1 : 'News',
               2 : 'Culture',
               3 : 'Work Life',
               4 : 'Internet',
               5 : 'Goverment',
               6 : 'Education',
               7 : 'Relationship',
               8 : 'Politics',
               9 : 'Self-Help'}

topic_num_to_list = out_dataframe[0].map(topic_list)

out_dataframe['Topic'] = topic_num_to_list

out_dataframe

0       Topic
questions                                                        
What will be the effects of demonitizing 500 an...  5   Goverment
Why is NASCAR a sport?                              5   Goverment
What's your view on the infamous Jayalalitha Sa...  5   Goverment
Should people over 94 not be allowed to vote?       9   Self-Help
What's the latest trend for SEO this 2014?          0  Technology
What were the major effects of the cambodia ear...  5   Goverment
Do virtual particles in vacuum really exist?        9   Self-Help
What is the salary scenario in pharmacovigilanc...  5   Goverment
Do all national servicemen in Singapore have to...  6   Education
What is the best way to learn computer language?    6   Education